language: node_js
node_js:
- '9'
- '8'
- '7'
- '6'
install:
- npm install
script:
- npm run test_coverage
- npm run lint
after_success:
- npm install -g codecov
- codecov
deploy:
  provider: npm
  email: kei.itof@gmail.com
  api_key:
    secure: f1uPU2N3Ioyu6FB6hlzzKlRsv7++JCZvXGlxyVqjRlNpDahhHoN4f6aM8e7nVqpzBTZvvQwWMBzNQDjVZgFFjpJ2W8NggB9oWqy55F00HcMo6nJGJ8n58taW1QTntQ9kHwAcz8sKjJvCbj/YUSqzVuqtTJ5zR47+qjMrIpG7mndtbPcvx1lLA5Z1jXOuitnvUAnCO0jkdhWSfM0AspcDqFIw2ap7QRqog/c1Ez/jhwYKPaI2QXcr9+A2wGzFQiP1CvPz9/XntEDbSeGB0hBgKFU2YPLXQ3mYBOH18YbdtLNydzRj5yyL/uA1RHh93yIazUDInnUsi58O74bIOZ+oM6Nnci0GC24SlGDdewQK+ZZxJXVxoIhlMKgjgDSMRUiy+E8gGcNbFFmtQYb9Mb+J14gmCGJdYBDjvvqAlC+vPrSY3YXUDs4+wboLSMowwAvo4sE4+Hd7ZQ3iwvYp+Q6vF2krVK1LceckSOZTBcN8xJ0hxYXrqHlV9LDPjvaQmYY1YagxtmaJAoLoRKO8VqI965T8YyEJarX6Ac7t5/jXEE3kID5t89XIuO0l2ovRacHIpZLc/34Op+AV+gIgo8/rlnoxx0aXFFndyUPxwsv/PFw++rLu2BOIrGT9FgJLBFApbvWADzJCzFoBMkHSGKhHgAE1C/3OSaW2lg/ZbYT6tCY=
  on:
    tags: true
    repo: nlibjs/content-type
notifications:
  slack:
    secure: NiPJjO+T4DSpfeoVyjpK5ohNu+8MWEcfKzoKA2zl7LhXZgh3hIcnAiCKwep9aXzkISfM3ARPqoSUNei3ybZm0zCNttgGMhtisKqk+ghC4N+7goTN9l5XJfdxM4hSWeEcRZuKXP12DgRCqxSdZNsNZUdh2nGTBKzcqtYBDJA3c8lK51lRY/VuH2gEmBFNq1N60NADochzchody1I/2ij8gW9J8Ma3RN+ZvxvgfCDAKvwnodBQrQFTaN/+7gDkGwh+It7jo5qgYus/jRLboMKir85KOZwO7xQaqrXvZq824yfrrZSWQrl9Z863w2eLIsXO/Np2iwUWqkmLG9YLv4zj04o70eyBBN5m7DgzaYFC6LTwmBtoog7BGD2In36HBJKLuchkjXk3d8lJHR3xpQL4+gv5rj0xQx7ZjrpFOOK2ZtcaBGVU1NblAzWuBeBKpSXn07F5ZAtqT2CbKbY+Y8cl/PwP661rjURz46OmHFozi9zFbsCSF4UYNNAfYTQha0W/uxmksuM9SFjLazKCCwEJ/vi0qYgXiPMhhNIbf65G1iCFradSofUQRzbPxwU5R2x9M6gxlS9g2C0XiBAF8FOBif3yOoj6IrtjVYK6NhG9SV+2OjlDYDq+dZYlCb0HOY6TFPCmPHDRKG4GGnfaRjhvXVrS6D69XurF05d5zX/4JJk=
